volumes:
  jugda_jekyll_data:
    name: jugda_jekyll_data
services:
  jekyll:
    image: jekyll/jekyll:4
    command: jekyll serve --watch --livereload --config _config.yml,_config.dev.yml
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll:cached
      - jugda_jekyll_data:/usr/local/bundle
